# Generated by Django 5.2.16 on 2026-07-15 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='is_gift',
        ),
    ]
