# Generated by Django 5.2.16 on 2026-07-15 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='writeup',
            options={'verbose_name_plural': 'WriteUps'},
        ),
    ]
