# Generated by Django 5.2.16 on 2026-07-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(max_length=5000),
        ),
    ]
