# Generated by Django 5.2.16 on 2026-07-17 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_contactmessage_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='writeup',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='writeups/'),
        ),
        migrations.AlterField(
            model_name='writeup',
            name='body',
            field=models.TextField(max_length=20000),
        ),
    ]
