# Generated by Django 5.2.16 on 2026-07-19 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_writeup_image_alter_writeup_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writeup',
            name='body',
            field=models.TextField(max_length=40000),
        ),
    ]
